services:
  # Backend API Service
  - type: web
    name: vibe-commerce-backend
    env: node
    region: oregon
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 30d

  # Frontend Static Site
  - type: web
    name: vibe-commerce-frontend
    env: static
    region: oregon
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://vibe-commerce-backend.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
